import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import kishore from "../assets/images/kishore.png";
import shape_wawes from "../assets/images/shape-wawes.svg";
import shape_circle from "../assets/images/shape-circle.svg";
import { RiLinkedinBoxLine, RiGithubLine, RiInstagramLine } from 'react-icons/ri';
function Banner() {
    return (_jsx(_Fragment, { children: _jsx("section", { className: "home section", id: "home", children: _jsxs("div", { className: "home__container container grid section__border", children: [_jsxs("div", { className: "home__data grid", children: [_jsxs("h1", { className: "home__title", children: ["Hi, I'm Kishore ", _jsx("br", {}), "Full Stack Web Developer ", _jsx("br", {}), _jsx("br", {})] }), _jsxs("div", { className: "home__blob grid", children: [_jsx("div", { className: "home__perfil", children: _jsx("img", { src: kishore, alt: "home perfil" }) }), _jsx("img", { src: shape_wawes, alt: "", className: "home__shape-wawes" }), _jsx("img", { src: shape_circle, alt: "", className: "home__shape-circle" })] }), _jsxs("ul", { className: "footer__social", children: [_jsx("li", { children: _jsx("a", { href: "https://www.linkedin.com/in/kishore-kumar-b8529b284/", target: "_blank", rel: "noopener noreferrer", className: "footer__social-link", children: _jsx(RiLinkedinBoxLine, {}) }) }), _jsx("li", { children: _jsx("a", { href: "https://github.com/kishore-404", target: "_blank", rel: "noopener noreferrer", className: "footer__social-link", children: _jsx(RiGithubLine, {}) }) }), _jsx("li", { children: _jsx("a", { href: "https://www.instagram.com/mr_poppy.23/?hl=en", target: "_blank", rel: "noopener noreferrer", className: "footer__social-link", children: _jsx(RiInstagramLine, {}) }) })] })] }), _jsxs("div", { className: "home__info", children: [_jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "BIOGRAPHY" }), _jsx("p", { className: "home__info-description", children: "Hi, I'm Kishore, Full Stack Web Developer. Passionate about building modern websites with React." })] }), _jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "CONTACT" }), _jsxs("p", { className: "home__info-description", children: ["Mylapore, Chennai ", _jsx("br", {}), "kishores.developer@gmail.com ", _jsx("br", {}), "+91 9500041579 ", _jsx("br", {})] })] }), _jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "ACHIEVEMENTS" }), _jsxs("p", { className: "home__info-description", children: ["Awarded Gold Medal for Academic Excellence in Computer Science 2024 ", _jsx("br", {}), "Selected as - Codeship Intern, 2025 ", _jsx("br", {})] })] })] }), _jsxs("div", { className: "home__info", children: [_jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "GRADUATING IN" }), _jsx("p", { className: "home__info-number", children: "2026" })] }), _jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "COMPLETED PROJECTS" }), _jsx("p", { className: "home__info-number", children: "3+" })] }), _jsxs("div", { children: [_jsx("h3", { className: "home__info-title", children: "COMPANIES WORKED FOR" }), _jsx("p", { className: "home__info-number", children: "2+" })] })] })] }) }) }));
}
export default Banner;
